CREATE TABLE Staff(
   id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
   email VARCHAR(128) NOT NULL,
   password VARCHAR(128) NOT NULL,
   firstName VARCHAR(255) NOT NULL,
   lastName VARCHAR(255) NOT NULL,
   street VARCHAR(255) NOT NULL,
   city VARCHAR(15) NOT NULL,
   state VARCHAR(15) NOT NULL,
   postCode VARCHAR(5) NOT NULL,
   country VARCHAR(15) NOT NULL,
   mobile VARCHAR(20)
);
