CREATE TABLE Suppliers(
   id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
   companyName VARCHAR(255) NOT NULL,
   email VARCHAR(128) NOT NULL,
   firstName VARCHAR(255) NOT NULL,
   lastName VARCHAR(255) NOT NULL,
   mobile VARCHAR(20) NOT NULL
);
